version: "3.9"
services:
  apache2:
    image: httpd:latest
    volumes:
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./htdocs:/usr/local/apache2/htdocs
      - ./conf/extra/:/usr/local/apache2/conf/extra
    ports:
      - "80:80"
      - "443:443"